### ISSUE TITLE
the relationship between this code and DeepVIO in IROS2019

### ISSUE THREAD

**Issue by tjj1998** [seungyeonson/DeepVIO#2]
Sorry to disturb you, Are you the author of [DeepVIO in IROS](https://arxiv.org/pdf/1906.11435.pdf)? Or this code is a reproduction? Anyway, thanks for your open source work.

**Comment by seungyeonson** [comment]
no, I am not author of DeepVIO. and I just study about that kind of visual inertial odometry with Deep learning.
